# docker compose file for productive useage
version: '3.8'
services:

  frontend:
    build:
      context: ./
      dockerfile: ./docker/nginx.Dockerfile
      args:
        - VITE_API_BASE_URL=localhost:8001
        - VITE_API_SCHEMA=http
    hostname: "frontend"

    ports:
      - "8021:80"
