name: Quality Assurance
on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: build project
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install dependencies
        run: |
          npm install

      - name: run linter
        run: |
          npm run lint

      - name: build app
        run: |
          npm run build

      - name: upload buileded app
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ./dist
